import pytest
from day_07.utils import Symbol


@pytest.fixture
def puzzle_input() -> list[list[str]]:
    """Puzzle input"""
    tachyon_manifold_diagram = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""
    return [
        [Symbol(char) for char in line.strip()]
        for line in tachyon_manifold_diagram.splitlines()
    ]
